CREATE TABLE reviews (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         service_request_id BIGINT NOT NULL UNIQUE,

                         customer_id BIGINT NOT NULL,

                         worker_profile_id BIGINT NOT NULL,

                         rating INT NOT NULL,

                         review_text VARCHAR(1000),

                         created_at TIMESTAMP NOT NULL,

                         updated_at TIMESTAMP NOT NULL,

                         CONSTRAINT fk_review_service_request
                             FOREIGN KEY (service_request_id)
                                 REFERENCES service_requests(id),

                         CONSTRAINT fk_review_customer
                             FOREIGN KEY (customer_id)
                                 REFERENCES users(id),

                         CONSTRAINT fk_review_worker_profile
                             FOREIGN KEY (worker_profile_id)
                                 REFERENCES worker_profiles(id)
);